### ISSUE TITLE
On different exes, game hangs when in main menu or dialogue

### ISSUE THREAD

**Issue by plzdonttrack** [Drahsid/FFXIITZA-FPS-Unlocker#16] opened 2018-10-23 03:08 UTC
If the program is open while on the main menu or when initializing conversation with an NPC, the game will freeze. Music will continue to play, but the screen will be stuck showing the last frame shown before the transition and the game will refuse any inputs I give it.

Tested will a variety of graphic options in-game, both English and Japanese languages, as well as differing frame rates and FOVs in the .ini including both Update 1 and 2 of the program.

I should note that opening the program while I already have control of Reks works as expected - the new framerate and FOV apply correctly. However, returning to the title screen or initializing conversation will lead to the hang.

Other notes,
* The pause menu is exempt from this error.
* If the program is active before opening the game, the game will freeze when the loading icon appears in the top-left corner.
* If the program is opened after the game is already on the title screen, the same freeze will occur.
* I have tried turning on the program only after the initial dialogue with Basch, but the same freeze will occur when talking to him again, or the nearby guard.

**Comment by Drahsid** [comment] 2018-10-23 03:21
I am unable to replicate this freezing.
Are  you in fullscreen mode? There seems to be some issues with that.

**Comment by plzdonttrack** [comment] 2018-10-23 03:40
Borderless fullscreen, and Windows 7 x64, for what it's worth.
I've tried deleting my .ini and I'm still getting the same results. Will continue to try different settings.

**Comment by Drahsid** [comment] 2018-10-23 03:42
I have just pushed a small update, try compiling and running that.

**Comment by plzdonttrack** [comment] 2018-10-23 03:49
All right, I'll try doing that real quick. In the meantime, I've noticed that I'm getting the exact opposite result with a clean Update 1 .ini, where the game freezes when I have control of Reks, but works fine during menus or dialogue (albeit at double speed).

**Comment by Drahsid** [comment] 2018-10-23 03:51
I think it's best to stick with the most recent updates, since the older update is less buggy in theory.
In your fpsconfig.ini, what are the requestedFrametimeMin values?

**Comment by plzdonttrack** [comment] 2018-10-23 03:55
All default.
With Update 2, that's
requestedMinFrameTime=90
requestedMinFrameTimeMenus=60
requestedMinFrameTimeNoFocus=24

**Comment by Drahsid** [comment] 2018-10-23 03:59
Could you record a short video of this issue?
Are you running the program as admin?

**Comment by plzdonttrack** [comment] 2018-10-23 04:19
Cool. Sorry that took a while. (It also turns out I'm inadequate at compiling things..)
But! Here's a quick video of the problem.
https://my.mixtape.moe/fpaems.flv

**Comment by plzdonttrack** [comment] 2018-10-23 04:29
Same error with the new .exe, deleted the old fpsconfig file as well.
Windows 7 x64
Intel i5 4690k @4.6 GHz

**Comment by Drahsid** [comment] 2018-10-23 04:38
You shouldn't be having any issues.
Lemme send you a more compatible version.

[FFXIITZAFPSU.zip](https://github.com/Drahsid/FFXIITZA-FPS-Unlocker/files/2504523/FFXIITZAFPSU.zip)
This one has SSE2 disabled so it should be able to run on any modern cpu.
Though you and I have the same cpu, so I'm sure this won't change anything unless you have SSE2 disabled in your bios.

**Comment by plzdonttrack** [comment] 2018-10-23 04:56
I should preface this with a big thank you for all the help you've put in.

However I've got the same error with that file as well.
I've tried taking off my overclock and reinstalling the game as well, but no dice.

**Comment by Drahsid** [comment] 2018-10-23 04:59
I'm not sure what's going wrong.
Please open this cheat table in Cheat Engine and tell me what "Total Time Scale", "In Game Multi", and the two "frametimemin" variables' values are.
Furthermore, if you could run it with the visual studio debugger, and tell me what line it breaks on when this crash happens.
[FFXII_TZA.zip](https://github.com/Drahsid/FFXIITZA-FPS-Unlocker/files/2504564/FFXII_TZA.zip)

**Comment by plzdonttrack** [comment] 2018-10-23 05:15
Okay, so while the program is running,
Total Time Scale = Jumps between 0.49xxx and 0.5xxx
In Game Multi = Always 1
Both Frame Time Min = 0.11 repeating

I'm clueless about the debugger, but I will try my hardest to get that information for you.
I've only tried Basch and the nearby soldier. I will edit this post when I get to the next save-point and try some others.

**Comment by Drahsid** [comment] 2018-10-23 05:16
0.11 repeating, or 0.011... ?

**Comment by Drahsid** [comment] 2018-10-23 05:33
Yeah I've tried everything but running an older OS, which would be an incredible amount of work. I cannot reproduce this issue, but there's got to be something causing it.
Try my config:
[fpsconfig.zip](https://github.com/Drahsid/FFXIITZA-FPS-Unlocker/files/2504622/fpsconfig.zip)

I don't think that'll fix the issue though.
I just want to confirm again that you're running the program as an Admin?
If you don't find anything via visual studio debugging I'll send over a botched down version of the program with some features disabled so we can get to the bottom of this.

**Comment by plzdonttrack** [comment] 2018-10-23 05:40
Hey, good call.
Running the program as Admin will crash the game even during the regular bits that tended to work for me. While that's not an improvement, that must mean something.

**Comment by Drahsid** [comment] 2018-10-23 05:45
Huh
That is incredibly strange.
Is your FFXII up to date?

**Comment by Drahsid** [comment] 2018-10-23 06:15
Huh
That is incredibly strange.
Is your FFXII up to date?
I messed with some of the build properties, perhaps this will work:
[FFXIITZAFPSU.zip](https://github.com/Drahsid/FFXIITZA-FPS-Unlocker/files/2504712/FFXIITZAFPSU.zip)

**Comment by plzdonttrack** [comment] 2018-10-23 06:40
I believe so. I have not replaced that or the other executable file with anything.
As it stands, I'll give it another go with another computer, and if there's a difference, I'll be sure to let you know. If not, I'll keep floating and trying any other versions you come out with, but I hate taking your focus away from the other bugs floating about.

**Comment by Drahsid** [comment] 2018-10-23 09:30
Hey something iust came to mind. When you start up the program, after it finds ffxii, and before it begins outputting "User has entered/edited menu" messages, dies it say something like "Failed to write instructions"

**Comment by plzdonttrack** [comment] 2018-10-23 18:50
Doesn't look like it.

When opening while at the title screen (taken before force-closing the program):
![on_mm](https://user-images.githubusercontent.com/44380873/47383357-c6f86580-d6c1-11e8-87dc-040d87607c81.png)
When opening when in control of Reks, then running into a cutscene (taken after force-closing the program):
![ingame](https://user-images.githubusercontent.com/44380873/47383393-d4adeb00-d6c1-11e8-9ca6-ad9fc82b104d.png)

**Comment by Drahsid** [comment] 2018-10-23 19:05
Hey- thanks for the update.
I realized a quick error in one of the messages that I was reporting in the console- that's fixed now.
That, however has nothing to do with this issue.
In a minute, I will edit this post and send over build of the program with the UI features disabled, and we'll see if it crashes then. In the mean time, do you have a Windows 10 rig you could test this on? Thanks.

**Comment by plzdonttrack** [comment] 2018-10-23 19:08
Nope, I don't have any ways to test on Windows 10. I'm just about to try installing on my other Windows 7 machine.
As a side-note, the console does have a bit of a grammatical error which states "User has is in a menu".

**Comment by Drahsid** [comment] 2018-10-23 19:35
Okay, so we've identified that the issue is not the framerate changing when we enter a menu.
Here's a version of the program with all of the in game instructions not being overwritten.
[FFXIITZAFPSU.zip](https://github.com/Drahsid/FFXIITZA-FPS-Unlocker/files/2507735/FFXIITZAFPSU.zip)
See if it still crashes.

**Comment by plzdonttrack** [comment] 2018-10-23 19:46
Holy man! It works.
No crashes on the menus, and the framerate and FOV still apply correctly!

**Comment by Drahsid** [comment] 2018-10-23 19:50
Okay so we've identified that the program is overwriting an important function.
With these disabled, the adaptive/locked mouse multi, and in game multiplier mods will not work.
Go back to an earlier version and try out this settings file:
`
requestedMinFrameTime=90
requestedMinFrameTimeMenus=60
requestedMinFrameTimeNoFocus=24
Fov=65
gamma=50
mainThreadUpdateCoef=1
igmState0Override=1
igmState1Override=2
igmState2Override=6
lockedMouseMulti=1
bEnableFullSpeedMode=false
bEnableAdaptiveIGM=false
bEnableAdaptiveMouse=false
bEnableLockedMouseMulti=false
bEnableTransitionSpeedRamp=true
`

**Comment by plzdonttrack** [comment] 2018-10-23 19:57
Using those setting with Update 2 freezes the game during cutscenes as per usual.

**Comment by Drahsid** [comment] 2018-10-23 19:58
Okay just for final confirmation, does this work?
[FFXIITZAFPSU.zip](https://github.com/Drahsid/FFXIITZA-FPS-Unlocker/files/2507794/FFXIITZAFPSU.zip)

**Comment by plzdonttrack** [comment] 2018-10-23 20:01
Yep, that works perfectly fine. No freezes. Allowed it to generate a new .ini.

**Comment by Drahsid** [comment] 2018-10-23 20:11
Okay I've identified the problem:
I think something is writing to your igm. I've identified some instructions but they don't really run.
This version has these included, see if it runs: 
[FFXIITZAFPSU.zip](https://github.com/Drahsid/FFXIITZA-FPS-Unlocker/files/2507814/FFXIITZAFPSU.zip)
If not, please open cheat engine, and right click the InGameMulti variable, following this select "Find out what writes to this address"
Following that, a new window will appear. Go ahead and do the normal thing, get control of Reks and talk to someone. Once the game crashes, go back to that menu, and click "Stop" then, if there's anything in the menu, one by one, right click these instructions, and click "Show in disassembler", next a memory window will appear, and selected on the top half with be the instruction. Right click the instruction, and click "Go to address"
List all of their addresses.

**Comment by Drahsid** [comment] 2018-10-23 20:28
Make sure to run the 64 bit version of cheat engine as admin.

**Comment by plzdonttrack** [comment] 2018-10-23 20:52
I can't say for sure if this is accurate. It kept spitting out an error that it could not attach after waiting 10 seconds, and repeating whenever I tried again. However, when I hit "No", it opened this window anyways. Here is what I could find:

Top Window
0022ACA7 - C7 05 E72AE501 0000803F - mov [0207D798],3F800000

Bottom Window
0022AC9D - F3 0F11 05 F32AE501  - movss [FFXII_TZA.exe+1F5D798],xmm0
0022ACA5 - EB 0A - jmp FFXII_TZA.exe+10ACB1
0022ACA7 - C7 05 E72AE501 0000803F - mov [FFXII_TZA.exe+1F5D798],3F800000 <<
0022ACB1 - E8 9A411300 - call FFXII_TZA.exe+23EE50
0022ACB6 - 85 C0  - test eax,eax

RAX=0000000000004000
RBX=0000000000000001
RCX=000000000CD0ADE0
RDX=0000000000000043
RSI=0000000000000000
RDI=0000000000000001
RSP=000000001CF2FD00
RBP=0000000000000000
RIP=000000000022ACB1
R8=0000000000000000
R9=0000000000000002
R10=0000000000000000
R11=000000001CF2FC10
R12=0000000000000000
R13=0000000000915C48
R14=0000000000000001
R15=0000000000000001

**Comment by plzdonttrack** [comment] 2018-10-23 20:54
Also, sorry. I'm not sure what you mean by "next a memory window will appear, and selected on the top half with be the instruction. Right click the instruction, and click "Go to address""

**Comment by Drahsid** [comment] 2018-10-23 20:55
The memory window is the one that looks like this
![image](https://user-images.githubusercontent.com/19179468/47390068-73e3da00-d6e4-11e8-99de-0492b0dc2571.png)

**Comment by plzdonttrack** [comment] 2018-10-23 20:58
I'm a bit confused of what information you need.
![untitled](https://user-images.githubusercontent.com/44380873/47390194-0334c180-d6d4-11e8-8145-8153f80962ab.png)

**Comment by Drahsid** [comment] 2018-10-23 20:59
It looks like your exe is different:
At 0022ACA7 I have this
add eax,ebp
where my mov [0207D789],3F800000 is at 0022AC27
In the memory viewer window, in the top half hit ctrl+g and tellme what opcode is at 0022AC27

**Comment by plzdonttrack** [comment] 2018-10-23 21:03
Like this?
![untitled2](https://user-images.githubusercontent.com/44380873/47390495-c917ef80-d6d4-11e8-970e-3d5f7a244c4f.png)

**Comment by Drahsid** [comment] 2018-10-23 21:04
How about this, my FFXII_TZA.exe's MD5 is F88350D39C8EDEECC3728A4ABC89289C
What's yours?

**Comment by plzdonttrack** [comment] 2018-10-23 21:07
Same as it was yesterday, at least. D032914AC59BAFDD62F038832CC14525

**Comment by Drahsid** [comment] 2018-10-23 21:10
We don't seem to have the same file.
Is your game out of date? Or perhaps there is a different exe for Win7?
I will edit this post with my exe

**Comment by Drahsid** [comment] 2018-10-24 21:11
Have you gotten any luck?

**Comment by plzdonttrack** [comment] 2018-11-19 19:49
Thanks so much for still supporting this issue, among all the other improvements you've made!
Unfortunately, the same issues persist in this new version as well -- the game will hang as before when in the main menu or during conversations. I have tried every version released since I last wrote.

**Comment by Drahsid** [comment] 2018-11-19 20:58
Hey. I cannot, nor have I received reports of others reproducing this issue. Are you using a pirated or Devueno-free version of the game?

**Comment by Drahsid** [comment] 2018-11-24 06:58
As described in issue #23, I discovered the particular MD5 of your file matches up with the CPY's denuvo-workaround. As such, I do not intent to fix this issue. Thank you for your cooperation.

**Closed by Drahsid** 2018-11-24 06:58 UTC
Labels: bad-md5, bug, invalid, piracy, wontfix
